"""empty message

Revision ID: 07d212f7a1d7
Revises: 26d0e0ee2536
Create Date: 2019-05-02 12:20:25.784006

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '07d212f7a1d7'
down_revision = '26d0e0ee2536'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        "CREATE TYPE event_repeat AS ENUM ('yearly', 'monthly', 'never');"
    )
    op.execute(
        "ALTER TABLE event ADD repeat event_repeat;"
    )
    op.drop_column('event', 'description')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        "ALTER TABLE event DROP COLUMN repeat;"
    )
    op.execute(
        "DROP TYPE event_repeat;"
    )
    op.add_column(
        'event',
        sa.Column(
            'description',
            sa.VARCHAR(),
            autoincrement=False,
            nullable=True
        )
    )
    # ### end Alembic commands ###

