"""Subscription id and on_shot

Revision ID: 0cfa89c0ef26
Revises: 608b65e9a333
Create Date: 2019-02-24 15:50:52.233375

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy import orm

from dolphin.models import Subscription


# revision identifiers, used by Alembic.
revision = '0cfa89c0ef26'
down_revision = '608b65e9a333'
branch_labels = None
depends_on = None


SUBSCRIPTION_PK_TITLE = 'subscription_pkey'


def upgrade():
    bind = op.get_bind()
    session = orm.Session(bind=bind)

    op.add_column(
        'subscription',
        sa.Column('created_at', sa.DateTime(), nullable=False)
    )
    op.add_column(
        'subscription',
        sa.Column('on_shot', sa.BOOLEAN(), nullable=True)
    )
    op.drop_constraint(
        SUBSCRIPTION_PK_TITLE,
        'subscription',
        type_='primary'
    )
    op.add_column(
        'subscription',
        sa.Column('id', sa.Integer(), nullable=True, primary_key=True)
    )

    subscriptions = session.query(Subscription).all()
    for index, subscription in enumerate(subscriptions):
        subscription.id = index
    session.commit()

    op.execute('ALTER TABLE subscription ADD PRIMARY KEY (id)')
    op.execute('ALTER TABLE subscription ALTER COLUMN id SET NOT NULL')


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('subscription', 'on_shot')
    op.drop_constraint(
        SUBSCRIPTION_PK_TITLE,
        'subscription',
        type_='primary'
    )
    op.drop_column('subscription', 'id')
    op.drop_column('subscription', 'created_at')
    op.execute(
        'ALTER TABLE subscription ADD PRIMARY KEY (subscribable_id, member_id)'
    )
    # ### end Alembic commands ###
