"""empty message

Revision ID: 0ecdd82ae075
Revises: a0be6b288a75
Create Date: 2019-04-15 17:43:13.817039

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0ecdd82ae075'
down_revision = 'a0be6b288a75'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('phase', sa.Column('description', sa.String(length=512), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('phase', 'description')
    # ### end Alembic commands ###
