"""empty message

Revision ID: 100c43e750ce
Revises: 1ac91251c69d
Create Date: 2019-01-27 11:46:20.779103

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy import Table, Integer, Column, orm
from sqlalchemy.ext.declarative import declarative_base

from dolphin.models import Skill, Phase


# revision identifiers, used by Alembic.
revision = '100c43e750ce'
down_revision = '1ac91251c69d'
branch_labels = None
depends_on = None


Base = declarative_base()

OldSkill = Table(Skill.__tablename__, Base.metadata,
    Column('phase_id', Integer),
    Column('resource_id', Integer)
)


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    session = orm.Session(bind=bind)

    op.execute('DELETE FROM skill')

    op.add_column('skill', sa.Column('id', sa.Integer(), nullable=False, unique=True))
    op.add_column('skill', sa.Column('title', sa.String(length=50), nullable=False))

    op.add_column('member', sa.Column('skill_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'member', 'skill', ['skill_id'], ['id'])

    op.add_column('phase', sa.Column('skill_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'phase', 'skill', ['skill_id'], ['id'])

    default_skill = Skill(title='Project Manager')
    session.add(default_skill)
    session.flush()

    phases = session.query(Phase).all()
    for phase in phases:
        phase.skill_id = default_skill.id

    op.drop_constraint('skill_phase_id_fkey', 'skill', type_='foreignkey')
    op.drop_constraint('skill_resource_id_fkey', 'skill', type_='foreignkey')
    op.drop_column('skill', 'phase_id')
    op.drop_column('skill', 'resource_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('skill', sa.Column('resource_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('skill', sa.Column('phase_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('skill_resource_id_fkey', 'skill', 'member', ['resource_id'], ['id'])
    op.create_foreign_key('skill_phase_id_fkey', 'skill', 'phase', ['phase_id'], ['id'])
    op.drop_column('skill', 'title')
    op.drop_column('skill', 'id')
    op.drop_constraint(None, 'phase', type_='foreignkey')
    op.drop_column('phase', 'skill_id')
    op.drop_constraint(None, 'member', type_='foreignkey')
    op.drop_column('member', 'skill_id')
    # ### end Alembic commands ###

