"""empty message

Revision ID: 23a6ce5a3736
Revises: bc68448183f5
Create Date: 2019-07-08 12:09:26.759225

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '23a6ce5a3736'
down_revision = 'bc68448183f5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'mule_task',
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('at', sa.DateTime(), nullable=True),
        sa.Column(
            'status',
            sa.Enum(
                'new',
                'in-progress',
                'expired',
                'success',
                'failed',
                name='mule_status_enum'
            ),
            nullable=True
        ),
        sa.Column('expired_at', sa.DateTime(), nullable=True),
        sa.Column('terminated_at', sa.DateTime(), nullable=True),
        sa.Column('type', sa.Unicode(length=50), nullable=False),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_table('return_to_triage_job',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('issue_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['mule_task.id'], ),
    sa.ForeignKeyConstraint(['issue_id'], ['issue.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column(
        'item',
        sa.Column(
            'need_estimate_timestamp',
            sa.DateTime(),
            nullable=True
        )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('item', 'need_estimate_timestamp')
    op.drop_table('return_to_triage_job')
    op.drop_table('mule_task')
    # ### end Alembic commands ###

