"""empty message
Revision ID: 26d0e0ee2536
Revises: 0ecdd82ae075
Create Date: 2019-04-29 11:16:35.270598
"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '26d0e0ee2536'
down_revision = '0ecdd82ae075'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('event_type',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.Unicode(), nullable=False),
    sa.Column('description', sa.Unicode(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('event',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_type_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.Unicode(), nullable=False),
    sa.Column('start_date', sa.DateTime(), nullable=False),
    sa.Column('end_date', sa.DateTime(), nullable=False),
    sa.Column('description', sa.Unicode(), nullable=True),
    sa.ForeignKeyConstraint(['event_type_id'], ['event_type.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('release', sa.Column('group_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'release', 'group', ['group_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'release', type_='foreignkey')
    op.drop_column('release', 'group_id')
    op.drop_table('event')
    op.drop_table('event_type')
    # ### end Alembic commands ###
