"""empty message

Revision ID: 2e13fae26b6a
Revises: 46062bdf066b
Create Date: 2019-03-13 17:28:09.858246

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy import orm

from dolphin.models import Release


# revision identifiers, used by Alembic.
revision = '2e13fae26b6a'
down_revision = '46062bdf066b'
branch_labels = None
depends_on = None


PROJECT_SECONDARY_MANAGER_ID_FKEY = 'project_secondary_manager_id_fkey'


def upgrade():
    bind = op.get_bind()
    session = orm.Session(bind=bind)

    op.add_column(
        'issue',
        sa.Column('modifiedBy', sa.Integer(), nullable=True)
    )
    op.add_column(
        'project',
        sa.Column('secondary_manager_id', sa.Integer(), nullable=True)
    )

    op.add_column(
        'release',
        sa.Column('launch_date', sa.DateTime(), nullable=True)
    )

    releases = session.query(Release)
    for release in releases:
        release.launch_date = release.cutoff

    session.commit()

    op.execute('ALTER TABLE release ALTER COLUMN launch_date SET NOT NULL;')
    op.create_foreign_key(
        PROJECT_SECONDARY_MANAGER_ID_FKEY,
        'project',
        'member',
        ['secondary_manager_id'],
        ['id']
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('release', 'launch_date')
    op.drop_constraint(
        PROJECT_SECONDARY_MANAGER_ID_FKEY,
        'project',
        type_='foreignkey'
    )
    op.drop_column('project', 'secondary_manager_id')
    op.drop_column('issue', 'modifiedBy')
    # ### end Alembic commands ###

