"""empty message

Revision ID: 337b551307f3
Revises: 4cfba8fe8a9c
Create Date: 2018-12-18 12:25:31.226229

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '337b551307f3'
down_revision = '4cfba8fe8a9c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('attachment',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('removed_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=True),
    sa.Column('caption', sa.String(length=500), nullable=True),
    sa.Column('_file', sa.JSON(), nullable=True),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('sender_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.ForeignKeyConstraint(['sender_id'], ['member.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('attachment')
    # ### end Alembic commands ###
