"""empty message

Revision ID: 33ff760bd18c
Revises: 0cfa89c0ef26
Create Date: 2019-02-25 12:04:32.259901

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '33ff760bd18c'
down_revision = '608b65e9a333'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('draft_issue', sa.Column('related_issue_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('draft_issue', 'related_issue_id')
    # ### end Alembic commands ###
