"""empty message

Revision ID: 36e21154d542
Revises: 23a6ce5a3736
Create Date: 2019-07-13 15:16:04.038389

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '36e21154d542'
down_revision = '23a6ce5a3736'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('issue', sa.Column('last_moving_time', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('issue', 'last_moving_time')
    # ### end Alembic commands ###
