"""empty message

Revision ID: 46062bdf066b
Revises: ef87b57af36e
Create Date: 2019-03-10 16:19:00.566996

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '46062bdf066b'
down_revision = 'ef87b57af36e'
branch_labels = None
depends_on = None


RELEASE_MANAGER_ID_FKEY = 'release_manager_id_fkey'


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'release',
        sa.Column('manager_id', sa.Integer(), nullable=False)
    )
    op.create_foreign_key(
        RELEASE_MANAGER_ID_FKEY,
        'release',
        'member',
        ['manager_id'],
        ['id']
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        RELEASE_MANAGER_ID_FKEY,
        'release',
        type_='foreignkey'
    )
    op.drop_column('release', 'manager_id')
    # ### end Alembic commands ###

