"""empty message

Revision ID: 4cfba8fe8a9c
Revises:
Create Date: 2018-12-18 11:51:00.167040

"""
from alembic import op
import sqlalchemy as sa
from restfulpy.orm import FakeJSON


# revision identifiers, used by Alembic.
revision = '4cfba8fe8a9c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organization',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('modified_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.Unicode(length=50), nullable=False),
    sa.Column('url', sa.Unicode(length=50), nullable=True),
    sa.Column('domain', sa.Unicode(length=50), nullable=True),
    sa.Column('logo', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_organization_title'), 'organization', ['title'], unique=True)
    op.create_table('restfulpy_task',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('new', 'success', 'in-progress', 'failed', name='task_status_enum'), nullable=True),
    sa.Column('fail_reason', sa.Unicode(length=4096), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('terminated_at', sa.DateTime(), nullable=True),
    sa.Column('type', sa.Unicode(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('email',
    sa.Column('template_filename', sa.Unicode(length=200), nullable=True),
    sa.Column('to', sa.Unicode(length=100), nullable=False),
    sa.Column('subject', sa.Unicode(length=256), nullable=False),
    sa.Column('cc', sa.Unicode(length=100), nullable=True),
    sa.Column('bcc', sa.Unicode(length=100), nullable=True),
    sa.Column('body', FakeJSON(), nullable=False),
    sa.Column('from_', sa.Unicode(length=100), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['restfulpy_task.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('invitation',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('modified_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('by_member_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.Enum('owner', 'member', name='roles'), nullable=False),
    sa.Column('accepted', sa.Boolean(), nullable=False),
    sa.Column('expired_date', sa.DateTime(), nullable=False),
    sa.Column('email', sa.Unicode(length=100), nullable=False),
    sa.ForeignKeyConstraint(['by_member_id'], ['member.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organization.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_invitation_email'), 'invitation', ['email'], unique=True)
    op.create_table('organization_member',
    sa.Column('member_id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.Enum('owner', 'member', name='roles'), nullable=False),
    sa.ForeignKeyConstraint(['member_id'], ['member.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organization.id'], ),
    sa.PrimaryKeyConstraint('member_id', 'organization_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('organization_member')
    op.drop_index(op.f('ix_invitation_email'), table_name='invitation')
    op.drop_table('invitation')
    op.drop_table('email')
    op.drop_table('restfulpy_task')
    op.drop_index(op.f('ix_organization_title'), table_name='organization')
    op.drop_table('organization')
    # ### end Alembic commands ###
