"""empty message

Revision ID: 508a09c9f43a
Revises: 5f206088190d
Create Date: 2019-06-25 14:03:06.881072

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '508a09c9f43a'
down_revision = '5f206088190d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('issue', 'is_done')
    op.add_column('item', sa.Column('is_done', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('item', 'is_done')
    op.add_column('issue', sa.Column('is_done', sa.BOOLEAN(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
