"""Renaming subscription fields

Revision ID: 73746e131fec
Revises: b92fe9cd33ec
Create Date: 2019-01-16 15:45:45.499475

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '73746e131fec'
down_revision = 'b92fe9cd33ec'
branch_labels = None
depends_on = None

OLD_FK_CONSTRAIN_NAME_SUBSCRIBABLE = 'subscription_subscribable_fkey'
OLD_FK_CONSTRAIN_NAME_MEMBER = 'subscription_member_fkey'

NEW_FK_CONSTRAIN_NAME_SUBSCRIBABLE = 'subscription_subscribable_id_fkey'
NEW_FK_CONSTRAIN_NAME_MEMBER = 'subscription_member_id_fkey'


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        OLD_FK_CONSTRAIN_NAME_SUBSCRIBABLE,
        'subscription',
        type_='foreignkey'
    )
    op.drop_constraint(
        OLD_FK_CONSTRAIN_NAME_MEMBER,
        'subscription',
        type_='foreignkey'
    )

    op.execute(
        f'ALTER TABLE subscription '
        f'RENAME COLUMN member TO member_id;'
    )

    op.execute(
        f'ALTER TABLE subscription '
        f'RENAME COLUMN subscribable TO subscribable_id;'
    )

    op.execute(
        f'ALTER TABLE subscription '
        f'ADD CONSTRAINT {NEW_FK_CONSTRAIN_NAME_SUBSCRIBABLE} '
        f'FOREIGN KEY (subscribable_id) REFERENCES subscribable(id);'
    )

    op.execute(
        f'ALTER TABLE subscription '
        f'ADD CONSTRAINT {NEW_FK_CONSTRAIN_NAME_MEMBER} '
        f'FOREIGN KEY (member_id) REFERENCES member(id);'
    )
    # ### end Alembic commands ###


def downgrade():
    pass
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        NEW_FK_CONSTRAIN_NAME_SUBSCRIBABLE,
        'subscription',
        type_='foreignkey'
    )

    op.drop_constraint(
        NEW_FK_CONSTRAIN_NAME_MEMBER,
        'subscription',
        type_='foreignkey'
    )

    op.execute(
        f'ALTER TABLE subscription '
        f'RENAME COLUMN member_id TO member;'
    )

    op.execute(
        f'ALTER TABLE subscription '
        f'RENAME COLUMN subscribable_id TO subscribable;'
    )

    op.execute(
        f'ALTER TABLE subscription '
        f'ADD CONSTRAINT {OLD_FK_CONSTRAIN_NAME_SUBSCRIBABLE} '
        f'FOREIGN KEY (subscribable) REFERENCES subscribable(id);'
    )

    op.execute(
        f'ALTER TABLE subscription '
        f'ADD CONSTRAINT {OLD_FK_CONSTRAIN_NAME_MEMBER} '
        f'FOREIGN KEY (member) REFERENCES member(id);'
    )
    # ### end Alembic commands ###
