"""empty message

Revision ID: 83cd6807fe8a
Revises: 5be0417cfc4c
Create Date: 2019-05-25 17:35:44.292098

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '83cd6807fe8a'
down_revision = '5be0417cfc4c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('item', sa.Column('_last_status_change', sa.DateTime(), nullable=True))
    op.add_column('item', sa.Column('_status', sa.Enum('in-progress', 'done', name='item_status'), nullable=True))
    op.drop_column('item', 'status')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('item', sa.Column('status', postgresql.ENUM('in-progress', 'done', name='item_status'), autoincrement=False, nullable=True))
    op.drop_column('item', '_status')
    op.drop_column('item', '_last_status_change')
    # ### end Alembic commands ###
