"""empty message

Revision ID: 84d5fef5976a
Revises: a2410e75c467
Create Date: 2019-05-13 14:33:29.207279

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '84d5fef5976a'
down_revision = 'a2410e75c467'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'dailyreport',
        sa.Column('item_id', sa.Integer(), nullable=False),
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('date', sa.Date(), nullable=False),
        sa.Column('hours', sa.Integer(), nullable=True),
        sa.Column('note', sa.Unicode(), nullable=True),
        sa.ForeignKeyConstraint(['item_id'], ['item.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('timecard')
    op.add_column(
        'item',
        sa.Column('estimated_hours', sa.Integer(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('item', 'estimated_hours')
    op.create_table(
        'timecard',
        sa.Column(
            'id',
            sa.INTEGER(),
            autoincrement=True,
            nullable=False
        ),
        sa.Column(
            'start_date',
            postgresql.TIMESTAMP(),
            autoincrement=False,
            nullable=False
        ),
        sa.Column(
            'end_date',
            postgresql.TIMESTAMP(),
            autoincrement=False,
            nullable=False
        ),
        sa.Column(
            'estimated_time',
            sa.INTEGER(),
            autoincrement=False,
            nullable=False
        ),
        sa.Column(
            'summary',
            sa.VARCHAR(),
            autoincrement=False,
            nullable=False
        ),
        sa.PrimaryKeyConstraint(
            'id',
            name='timecard_pkey'
        )
    )
    op.drop_table('dailyreport')
    # ### end Alembic commands ###
