"""empty message

Revision ID: 936c432ce331
Revises: 83cd6807fe8a
Create Date: 2019-05-30 10:58:52.877648

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '936c432ce331'
down_revision = '83cd6807fe8a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('issue', 'due_date')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'issue',
        sa.Column(
            'due_date',
            postgresql.TIMESTAMP(),
            autoincrement=False,
            nullable=False
        )
    )
    # ### end Alembic commands ###

