"""empty message

Revision ID: 9659db034551
Revises: ea2e299a81af
Create Date: 2019-02-07 10:28:01.821649

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9659db034551'
down_revision = 'ea2e299a81af'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('related_issue',
    sa.Column('issue_id', sa.Integer(), nullable=False),
    sa.Column('related_issue_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['issue_id'], ['issue.id'], ),
    sa.ForeignKeyConstraint(['related_issue_id'], ['issue.id'], ),
    sa.PrimaryKeyConstraint('issue_id', 'related_issue_id')
    )
    op.create_table('activity',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('modified_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.DateTime(), nullable=True),
    sa.Column('end_time', sa.DateTime(), nullable=True),
    sa.Column('description', sa.Unicode(length=256), nullable=True),
    sa.ForeignKeyConstraint(['item_id'], ['item.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('activity')
    op.drop_table('related_issue')
    # ### end Alembic commands ###
