"""empty message

Revision ID: a0be6b288a75
Revises: 8b5f59f842ae
Create Date: 2019-04-13 19:37:29.984814

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a0be6b288a75'
down_revision = '8b5f59f842ae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('phase_order_key', 'phase', type_='unique')
    op.add_column('release', sa.Column('room_id', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('release', 'room_id')
    op.create_unique_constraint('phase_order_key', 'phase', ['order'])
    # ### end Alembic commands ###
