"""empty message

Revision ID: a2410e75c467
Revises: 07d212f7a1d7
Create Date: 2019-05-09 14:54:59.879316

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a2410e75c467'
down_revision = '07d212f7a1d7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('timecard',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.DateTime(), nullable=False),
    sa.Column('end_date', sa.DateTime(), nullable=False),
    sa.Column('estimated_time', sa.Integer(), nullable=False),
    sa.Column('summary', sa.Unicode(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('item', sa.Column('description', sa.String(), nullable=True))
    op.add_column('item', sa.Column('end_time', sa.DateTime(), nullable=True))
    op.add_column('item', sa.Column('start_time', sa.DateTime(), nullable=True))
    op.add_column('item', sa.Column('status', sa.Enum('to-do', 'in-progress', 'on-hold', 'delayed', 'complete', name='item_status'), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('item', 'status')
    op.drop_column('item', 'start_time')
    op.drop_column('item', 'end_time')
    op.drop_column('item', 'description')
    op.drop_table('timecard')
    # ### end Alembic commands ###
