"""empty message

Revision ID: b4aea59e6385
Revises: 100c43e750ce
Create Date: 2019-01-31 13:11:58.389891

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b4aea59e6385'
down_revision = '100c43e750ce'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('item', sa.Column('id', sa.Integer(), nullable=False, unique=True, primary_key=True))
    op.create_unique_constraint(None, 'item', ['phase_id', 'issue_id', 'member_id'])

    op.create_table('activity',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('modified_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.DateTime(), nullable=True),
    sa.Column('end_time', sa.DateTime(), nullable=True),
    sa.Column('description', sa.Unicode(length=256), nullable=True),
    sa.ForeignKeyConstraint(['item_id'], ['item.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'item', type_='unique')
    op.drop_table('activity')
    op.drop_column('item', 'id')
    # ### end Alembic commands ###
