"""Added unique constrain

Revision ID: b92fe9cd33ec
Revises: b9ff7f16e411
Create Date: 2019-01-13 17:49:29.338276

"""
from alembic import op


# revision identifiers, used by Alembic.
revision = 'b92fe9cd33ec'
down_revision = 'b9ff7f16e411'
branch_labels = None
depends_on = None

GROUP_TITLE_UNIQUE_CONSTRAIN_NAME = 'group_title_key'


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(
        GROUP_TITLE_UNIQUE_CONSTRAIN_NAME,
        'group',
        ['title']
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        GROUP_TITLE_UNIQUE_CONSTRAIN_NAME,
        'group',
        type_='unique'
    )
    # ### end Alembic commands ###
