"""draftissue_issue table

Revision ID: c5b39d97cc75
Revises: 10f8c26a45d0
Create Date: 2019-03-02 18:14:39.474436

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c5b39d97cc75'
down_revision = '10f8c26a45d0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'draftissue_issue',
        sa.Column('draft_issue_id', sa.Integer(), nullable=False),
        sa.Column('related_issue_id', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(['draft_issue_id'], ['draft_issue.id'], ),
        sa.ForeignKeyConstraint(['related_issue_id'], ['issue.id'], ),
        sa.PrimaryKeyConstraint('draft_issue_id', 'related_issue_id'),
    )
    op.drop_column('draft_issue', 'related_issue_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'draft_issue',
        sa.Column(
            'related_issue_id',
            sa.INTEGER(),
            autoincrement=False,
            nullable=True
        )
    )
    op.drop_table('draftissue_issue')
    # ### end Alembic commands ###

