"""Add to-do to issues_status type

Revision ID: e371cfc0cb1e
Revises: daaef7a0d527
Create Date: 2019-01-09 14:26:23.243221

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e371cfc0cb1e'
down_revision = 'daaef7a0d527'
branch_labels = None
depends_on = None


def upgrade():
    # ALTER TYPE is not transactional so the next line is needed
    op.execute('COMMIT')
    op.execute('ALTER TYPE issues_status ADD VALUE \'to-do\'')
    op.execute('ALTER TYPE issues_status ADD VALUE \'complete\'')


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
