"""Making subscriptions.seen_at nullable

Revision ID: f026530141f2
Revises: 1ac91251c69d
Create Date: 2019-01-19 15:41:02.166586

"""
from alembic import op
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision = 'f026530141f2'
down_revision = '1ac91251c69d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        'subscription',
        'seen_at',
        existing_type=postgresql.TIMESTAMP(),
        nullable=True
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        'subscription',
        'seen_at',
        existing_type=postgresql.TIMESTAMP(),
        nullable=False
    )
    # ### end Alembic commands ###
