"""empty message

Revision ID: fbf36ff71e51
Revises: 2e13fae26b6a
Create Date: 2019-03-16 15:46:22.880422

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fbf36ff71e51'
down_revision = '2e13fae26b6a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project', sa.Column('modifiedBy', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('project', 'modifiedBy')
    # ### end Alembic commands ###
